[init]
name = "OpenRC"
is_available = ["/sbin/rc-service", "-l"]
restart = ["/etc/tedge/rc-service_restart-wrapper", "{}", "restart"]
stop =  ["/sbin/rc-service", "{}", "stop"]
enable =  ["/sbin/rc-update", "add", "{}"]
disable =  ["/sbin/rc-update", "delete", "{}"]
is_active = ["/sbin/rc-service", "{}", "status"]
