#!/bin/bash

### BEGIN INIT INFO
# Provides:             apama
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Apama correlator with thin-edge connectivity
# Description:
# Starts a correlator with a thin-edge project
# Does nothing if /etc/tedge/apama/project doesn't exist
### END INIT INFO

set -e

APAMAHOME=/opt/softwareag/Apama
APAMAPROJECT=/etc/tedge/apama/project
PIDFILE=/var/run/correlator.pid
LOGFILE=/var/log/correlator.log

if [[ ! -d "$APAMAPROJECT" ]];
then
    echo "No project located in /etc/tedge/apama/project.  To use this service ensure there is an Apama project located in that directory."
    exit 1
fi

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

case "$1" in
  start)
        if init_is_upstart; then
            exit 1
        fi
	echo "Attempting to start correlator"
        if start-stop-daemon --start --quiet --oknodo --background  --make-pidfile --pidfile ${PIDFILE} --exec ${APAMAHOME}/bin/apama_env -- correlator --config ${APAMAPROJECT}/config ; then
            echo "Success"
	    log_end_msg 0
        else
	    echo "Project is already running. Did not start."
            log_end_msg 1
        fi
        ;;
  stop)
        if init_is_upstart; then
            exit 0
        fi
        echo "Stopping correlator"
        if start-stop-daemon --stop --quiet --oknodo --pidfile ${PIDFILE}; then
            log_end_msg 0
            rm -f ${PIDFILE}
	    echo "Success"
        else
            log_end_msg 1
        fi
        ;;
  reload|force-reload)
        if init_is_upstart; then
            exit 1
        fi
        echo "Attempting to reload correlator"
        if start-stop-daemon --stop --signal HUP --quiet --oknodo --pidfile $PIDFILE; then
            log_end_msg 0
            echo "Success"
        else
            log_end_msg 1
        fi
        ;;
  restart)
        if init_is_upstart; then
            exit 1
        fi
        echo "Attempting to restart correlator"
        if start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile ${PIDFILE}; then
            rm -f ${PIDFILE}
            echo "Stopped running correlator"
        fi
        if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile ${PIDFILE} --exec ${APAMAHOME}/bin/apama_env -- correlator --config ${APAMAPROJECT}/config ; then
            echo "Started new correlator"
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
  status)
        if init_is_upstart; then
            exit 1
        fi
        status_of_proc -p ${PIDFILE} ${APAMAHOME}/bin/correlator correlator && exit 0 || exit $?
        ;;

  *)
        #log_action_msg "Usage: service apama {start|stop|reload|force-reload|restart|status}"
        exit 1
esac
exit 0
