services:
  gateway:
    # Image is maintained under: https://github.com/thin-edge/opcua-device-gateway-container
    image: ghcr.io/thin-edge/opcua-device-gateway:20241107.1636
    restart: always
    environment:
      # thin-edge.io MQTT broker
      - MQTT_BROKER=host.containers.internal:1883
    volumes:
      - opcua_data:/data
      # Provide access to thin-edge.io configuration
      - /etc/tedge:/etc/tedge
      - /etc/tedge/device-certs:/etc/tedge/device-certs
    networks:
      - backend

volumes:
  opcua_data:

networks:
  backend:
