#!/bin/sh

echo "tedge update hook: stop and snapshot"

set -e

# mark current thin-edge container for rollback
echo "Renaming container"
docker container rename "thin-edge" "thin-edge_snapshot"
 
# disconnect all clouds (in that example we know C8Y is connected)
# could be improved to automatically loop over all currently connected clouds
echo "Disconnecting C8Y"
sudo tedge disconnect c8y

# export current config for new container
echo "Exporting tedge config"
cp -r /etc/tedge /tmp/tedge-update-store/

echo "Hook1 done"
exit 0 # success 
